export const CFG = {
  chassisSize:       { x: 1.0, y: 0.5, z: 2.2 },
  chassisMass:       800,
  wheelRadius:       0.4,
  wheelWidth:        0.3,
  wheelAxisOffset:   { x: 0.9, y: -0.2, z: 1.4 },
  engineForce:       2800,
  nitroForce:        5400,
  brakingForce:      90,
  maxSteer:          0.55,
  steerSpeed:        0.06,
  cameraHeight:      4.0,
  cameraDistance:    9.0,
  groundFriction:    0.9,
  raceLaps:          4,
  maxNitro:          100,
  nitroDrainRate:    35,
  nitroRegenRate:    8,
};
